version: '2'

services:
  db:
    build: dockerfiles/postgres/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - persistent-storage:/var/lib/postgresql/data
  web:
    build: dockerfiles/django/
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "python3 manage.py makemigrations webclient && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

volumes:
  persistent-storage:
