version: '2'

services:
  db:
    build: dockerfiles/postgres/
  web:
    build: dockerfiles/django/
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /home/jdas:/home/jdas
    working_dir: /app
    command: bash -c "cp -r annotable/small-tomatoes/ webclient/static/ && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

networks:  
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
