version: '2'

services:
  db:
    build: dockerfiles/postgres/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - persistent-storage:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  grafana:
    build: dockerfiles/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    links:
      - db
    environment:
      GF_USERS_DEFAULT_THEME: "light"
    
  martin: 
    image: urbica/martin
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/agdss
  web:
    build: dockerfiles/django/
    ports:
      - "127.0.0.1:8273:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "python3 manage.py makemigrations webclient && python3 manage.py makemigrations earthpod && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

volumes:
  persistent-storage:
