version: '2'

services:
  db:
    build: dockerfiles/postgres/
    volumes:
      - persistent-storage:/var/lib/postgresql/data
  web:
    build: dockerfiles/django/
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "python3 manage.py makemigrations webclient && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

networks:  
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
volumes:
  persistent-storage:
