# Generated by Django 3.2.6 on 2021-09-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pod_id', models.IntegerField()),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarthPodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('atmos_temperature', models.FloatField(blank=True, null=True)),
                ('atmos_relative_humidity', models.FloatField(blank=True, null=True)),
                ('atmos_pressure', models.FloatField(blank=True, null=True)),
                ('soil_temperature', models.FloatField(blank=True, null=True)),
                ('soil_relative_humidity', models.FloatField(blank=True, null=True)),
                ('soil_moisture_2cm', models.FloatField(blank=True, null=True)),
                ('soil_moisture_5cm', models.FloatField(blank=True, null=True)),
                ('earth_pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earthpod.earthpod')),
            ],
        ),
    ]
