# Generated by Django 3.2.6 on 2021-09-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthpod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthpoddata',
            name='datetime_pod',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
