# Generated by Django 3.2.6 on 2021-10-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthpod', '0002_earthpoddata_datetime_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthpoddata',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthpoddata',
            name='light_analog',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
