apiVersion: 1

datasources:
- name: pg
  type: postgres
  url: db:5432
  access: proxy
  password: postgres
  user: postgres
  database: agdss
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
  version: 1
  editable: true